// <auto-generated />
using System;
using IntegrationOps.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegrationOps.Api.Data.Migrations
{
    [DbContext(typeof(IntegrationOpsDbContext))]
    [Migration("20260907183837_IdempotentIntegrationRunIntake")]
    partial class IdempotentIntegrationRunIntake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegrationOps.Api.Data.IntegrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("completed_at");

                    b.Property<byte[]>("IdempotencyKeyHash")
                        .HasColumnType("bytea")
                        .HasColumnName("idempotency_key_hash");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("operation");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("partner");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp(6) with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<byte[]>("RequestFingerprint")
                        .HasColumnType("bytea")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_integration_runs");

                    b.HasIndex("IdempotencyKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_integration_runs_idempotency_key_hash")
                        .HasFilter("idempotency_key_hash IS NOT NULL");

                    b.HasIndex("ReceivedAt", "Id")
                        .HasDatabaseName("ix_integration_runs_received_at_id");

                    b.ToTable("integration_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_integration_runs_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_integration_runs_completed_at", "completed_at IS NULL OR (isfinite(completed_at) AND completed_at BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00')");

                            t.HasCheckConstraint("ck_integration_runs_completion_order", "completed_at IS NULL OR completed_at >= received_at");

                            t.HasCheckConstraint("ck_integration_runs_idempotency_key_hash_length", "idempotency_key_hash IS NULL OR octet_length(idempotency_key_hash) = 32");

                            t.HasCheckConstraint("ck_integration_runs_intake_metadata", "(idempotency_key_hash IS NULL AND request_fingerprint IS NULL) OR (idempotency_key_hash IS NOT NULL AND request_fingerprint IS NOT NULL)");

                            t.HasCheckConstraint("ck_integration_runs_operation", "char_length(operation) > 0");

                            t.HasCheckConstraint("ck_integration_runs_partner", "char_length(partner) > 0");

                            t.HasCheckConstraint("ck_integration_runs_received_at", "isfinite(received_at) AND received_at BETWEEN TIMESTAMPTZ '0001-01-01 00:00:00+00' AND TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'");

                            t.HasCheckConstraint("ck_integration_runs_record_count", "record_count >= 0");

                            t.HasCheckConstraint("ck_integration_runs_request_fingerprint_length", "request_fingerprint IS NULL OR octet_length(request_fingerprint) = 32");

                            t.HasCheckConstraint("ck_integration_runs_status", "status IN ('Pending', 'Succeeded', 'Failed')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
